# SPDX-License-Identifier: BSD-3-Clause
---
- name: Ensure postfix is installed.
  ansible.builtin.apt:
    name: postfix
    state: present

- ansible.builtin.import_tasks: postfix_config.yml
  when: postfix_manage_config

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"
